/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardVehiclesRouteImport } from './routes/dashboard.vehicles'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardKeysRouteImport } from './routes/dashboard.keys'
import { Route as DashboardDocsRouteImport } from './routes/dashboard.docs'
import { Route as ApiDecodeRouteImport } from './routes/api.decode'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminKeysRouteImport } from './routes/admin.keys'
import { Route as DashboardVehiclesIdRouteImport } from './routes/dashboard.vehicles.$id'

const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardVehiclesRoute = DashboardVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeysRoute = DashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocsRoute = DashboardDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiDecodeRoute = ApiDecodeRouteImport.update({
  id: '/api/decode',
  path: '/api/decode',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKeysRoute = AdminKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardVehiclesIdRoute = DashboardVehiclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardVehiclesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/logs': typeof AdminLogsRoute
  '/api/decode': typeof ApiDecodeRoute
  '/dashboard/docs': typeof DashboardDocsRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/vehicles/$id': typeof DashboardVehiclesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/logs': typeof AdminLogsRoute
  '/api/decode': typeof ApiDecodeRoute
  '/dashboard/docs': typeof DashboardDocsRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/vehicles/$id': typeof DashboardVehiclesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/logs': typeof AdminLogsRoute
  '/api/decode': typeof ApiDecodeRoute
  '/dashboard/docs': typeof DashboardDocsRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/vehicles/$id': typeof DashboardVehiclesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/admin/keys'
    | '/admin/logs'
    | '/api/decode'
    | '/dashboard/docs'
    | '/dashboard/keys'
    | '/dashboard/profile'
    | '/dashboard/vehicles'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/vehicles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/admin/keys'
    | '/admin/logs'
    | '/api/decode'
    | '/dashboard/docs'
    | '/dashboard/keys'
    | '/dashboard/profile'
    | '/dashboard/vehicles'
    | '/admin'
    | '/dashboard'
    | '/dashboard/vehicles/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/admin/keys'
    | '/admin/logs'
    | '/api/decode'
    | '/dashboard/docs'
    | '/dashboard/keys'
    | '/dashboard/profile'
    | '/dashboard/vehicles'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/vehicles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ApiDecodeRoute: typeof ApiDecodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/vehicles': {
      id: '/dashboard/vehicles'
      path: '/vehicles'
      fullPath: '/dashboard/vehicles'
      preLoaderRoute: typeof DashboardVehiclesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/keys': {
      id: '/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof DashboardKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/docs': {
      id: '/dashboard/docs'
      path: '/docs'
      fullPath: '/dashboard/docs'
      preLoaderRoute: typeof DashboardDocsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/decode': {
      id: '/api/decode'
      path: '/api/decode'
      fullPath: '/api/decode'
      preLoaderRoute: typeof ApiDecodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/keys': {
      id: '/admin/keys'
      path: '/keys'
      fullPath: '/admin/keys'
      preLoaderRoute: typeof AdminKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/vehicles/$id': {
      id: '/dashboard/vehicles/$id'
      path: '/$id'
      fullPath: '/dashboard/vehicles/$id'
      preLoaderRoute: typeof DashboardVehiclesIdRouteImport
      parentRoute: typeof DashboardVehiclesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminKeysRoute: typeof AdminKeysRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminKeysRoute: AdminKeysRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardVehiclesRouteChildren {
  DashboardVehiclesIdRoute: typeof DashboardVehiclesIdRoute
}

const DashboardVehiclesRouteChildren: DashboardVehiclesRouteChildren = {
  DashboardVehiclesIdRoute: DashboardVehiclesIdRoute,
}

const DashboardVehiclesRouteWithChildren =
  DashboardVehiclesRoute._addFileChildren(DashboardVehiclesRouteChildren)

interface DashboardRouteChildren {
  DashboardDocsRoute: typeof DashboardDocsRoute
  DashboardKeysRoute: typeof DashboardKeysRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardVehiclesRoute: typeof DashboardVehiclesRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDocsRoute: DashboardDocsRoute,
  DashboardKeysRoute: DashboardKeysRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardVehiclesRoute: DashboardVehiclesRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ApiDecodeRoute: ApiDecodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
